sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - source
env:
  global:
    - GH_REPO="dpwright/danikki"
    - REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
before_script:
  - cd 出力
  - git checkout master
  - git pull origin master
  - rm -rf *
  - cd ..
install:
  - npm install
script:
  - npm run build
after_success:
  - cd 出力
  - git status
  - git add -A
  - git config --global user.email "dani@dpwright.com"
  - git config --global user.name "Daniel P. Wright"
  - git commit -m "自動作成 $(date '+%m/%d/%y %H:%M')"
  - git push "$REPO_URL" master | grep -v http
  - cd ..
